### PR TITLE
Merge Chad's changes from https://github.com/broccolijs/broccoli-filter/pull/28

### PR DESCRIPTION
**Pull request by zackthehuman**
This merge's Chad's changes from https://github.com/broccolijs/broccoli-filter/pull/28 into this plugin.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Awesome! Will review and merge if good tonight. This plus @kellyselden fix of hash for dep may let us get babel/jshint persistent out this weekend!

**Comment by zackthehuman** [comment]
That's awesome! Let me know if there is anything I can do.

**Comment by stefanpenner** [comment]
* Ember-cli's internal config replacer needs to stop invaliding on each rebuild 
* broccoli-jshint broccoli-jscs both also need to stop always rebuilding

Something more related to this, is getting broccoli-babel-transpiler using this pr

**Comment by stefanpenner** [comment]
@zackthehuman window support has landed for hash-for-dep https://github.com/stefanpenner/hash-for-dep/commit/335d69b3fc7d6ed19b6b94551a7d5e943e084f8c

**Comment by zackthehuman** [comment]
@stefanpenner Shall I bump the version in package.json in this branch?

**Comment by stefanpenner** [comment]
Yup and remove the windows check.

**Comment by zackthehuman** [comment]
Bumping to 1.0.0 of hash-for-dep break the tests. On my mac this happens: `Error: Cannot find module '/User.//package.json'`.

I haven't tracked down the source of the issue yet, though.

**Comment by kellyselden** [comment]
@zackthehuman It looks like my change may have broke OSX. @stefanpenner We may need to add OSX testing in Travis to prevent this.

**Comment by stefanpenner** [comment]
merged the two git histories (as best as possible) and merged manually.

**Comment by stefanpenner** [comment]
looking into the OSX issue now

**Comment by stefanpenner** [comment]
@zackthehuman & @kellyselden I am unable to replicate that issue on OSX

@zackthehuman can you share reproduction steps?

**Comment by zackthehuman** [comment]
@stefanpenner & @kellyselden Maybe my OSX issue was a fluke. I just pulled the latest from master and that branch works fine. Previously the steps to reproduce were: `npm install` and then `npm test`. Anyway, looks good to me now.

**Comment by stefanpenner** [comment]
> Anyway, looks good to me now.

lets assume a fluke, but keep in on our radar.

Just a headsup, im working to fix the last bugs with using this and the broccoli-babel-transpiler then i'll move on the jshint and jscs.

**Pull request merged**
