### PR TITLE
Improve boot

### PR DESCRIPTION
**Pull request by stefanpenner**
takes warm boot of stress-app babel from (2108ms - 2600ms) -> 1400ms

Some more perf for warm and cold boots: https://github.com/stefanpenner/async-disk-cache/issues/4 coming soon.

### CODE REVIEW

**Comment by chadhietala** [comment]
LGTM

**Comment by stefanpenner** [comment]
this also improves cold boot abit

**Comment by rwjblue** [comment]
:+1:

**Comment by stefanpenner** [comment]
released at v1.0.5

**Pull request merged**
