### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by twokul**

### CODE REVIEW

**Comment by stefanpenner** [comment]
awesome

**Comment by stefanpenner** [comment]
we should add some additional tests:

* that ensure changing an option (like modules: true, to false) invalidates
* that the changing of the contents of a file invalidates

**Comment by twokul** [comment]
@stefanpenner absolutely, just the first pass

**Comment by stefanpenner** [comment]
sounds good, you are a collab. Feel free to merge, and move to the next.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/broccoli-persistent-filter/pull/8

**Pull request closed without merging**
