### PR TITLE
Remove crypto package.

### LINKED ISSUE #127: Crypto dependency warning
```
warning ember-cli-babel > broccoli-babel-transpiler > broccoli-persistent-filter > crypto@0.0.3: 
This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, 
you should switch to the one that's built-in.
```

### PR DESCRIPTION
**Pull request by blimmer**
This will now use the native node implementation.
Fixes #127

cc @rwjblue

### CODE REVIEW

**Comment by blimmer** [comment]
According to [the docs](https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm) this has been available since v0.1.92 so I think this won't cause problems for anyone.

**Comment by rwjblue** [comment]
No clue why we ended up with this as a dependency. Thanks for fixing! 

I'll merge and release when I'm back at my computer...

**Comment by blimmer** [comment]
No problem - glad to help!

**Comment by stefanpenner** [comment]
released as v1.4.3 🎉

**Pull request merged**
